language: python
python:
    - 2.7
install:
    - pip install -r requirements.txt

script:
    - paver lint
    - nose2 --with-coverage --coverage-report=term-missing --config dev_configs/nose2.cfg
    - cd pronunciation_master/src/tests ; lettuce --verbosity=2
