language: python
python:
    - 2.7
install:
    - pip install -r requirements.txt
services:
    . postgresql
before_script:
    - psql -c 'CREATE ROLE tester WITH CREATEDB LOGIN;' -U postgres
script:
    - paver lint
    - nose2 --with-coverage --coverage-report=term-missing --config dev_configs/nose2.cfg
    - cd pronunciation_master/tests ; lettuce --verbosity=2
